
import { User, Category, Lesson, Achievement, Friend, ActivityItem } from "@/types";

// Mock User Data
export const mockUser: User = {
  id: "user1",
  name: "Alex Johnson",
  email: "alex@example.com",
  avatar: "/placeholder.svg",
  country: "United States",
  language: "English",
  birthday: "1990-01-15",
  occupation: "Product Manager",
  reason: "Improve public speaking",
  level: 3,
  xp: 750,
  streak: 7,
  totalLearningTime: 128,
  dailyGoalMinutes: 10,
  referrals: 2,
  createdAt: "2023-05-15T10:30:00Z",
};

// Mock Categories and Lessons
export const mockCategories: Category[] = [
  {
    id: "impromptu",
    name: "Impromptu Speaking",
    description: "Learn to speak clearly and confidently without preparation",
    icon: "🗣️",
    color: "bg-lingo-blue",
    image: "/placeholder.svg",
    requiredLevel: 1,
    lessons: [
      {
        id: "impromptu1",
        title: "Quick Introduction",
        description: "Learn to introduce yourself effectively",
        prompt: "Tell me about your favorite hobby for 30 seconds.",
        focusArea: "Speaking off-the-cuff",
        durationSeconds: 30,
        level: 1,
        isCompleted: true,
      },
      {
        id: "impromptu2",
        title: "Descriptive Speaking",
        description: "Practice detailed observation skills",
        prompt: "Describe the view from your window right now for 45 seconds.",
        focusArea: "Descriptive language",
        durationSeconds: 45,
        level: 1,
        isCompleted: false,
      },
      {
        id: "impromptu3",
        title: "Opinion Piece",
        description: "Share your thoughts on a topic",
        prompt: "What's one small change you'd like to see in your neighborhood? Speak for 1 minute.",
        focusArea: "Expressing opinions",
        durationSeconds: 60,
        level: 2,
        isCompleted: false,
      },
      {
        id: "impromptu4",
        title: "Storytelling",
        description: "Share a brief personal story",
        prompt: "Tell a short story about a memorable object you own.",
        focusArea: "Narrative skills",
        durationSeconds: 60,
        level: 2,
        isCompleted: false,
      },
      {
        id: "impromptu5",
        title: "Quick Debate",
        description: "Argue a position with limited preparation",
        prompt: "Argue for or against the use of social media in schools for 1 minute 30 seconds.",
        focusArea: "Quick argumentation",
        durationSeconds: 90,
        level: 3,
        isCompleted: false,
      },
      {
        id: "impromptu6",
        title: "Creative Response",
        description: "Think creatively on your feet",
        prompt: "If you could have any superpower, what would it be and why? Explain for 2 minutes.",
        focusArea: "Creative thinking and justification",
        durationSeconds: 120,
        level: 3,
        isCompleted: false,
      },
      {
        id: "impromptu7",
        title: "Problem Solving",
        description: "Address a common issue",
        prompt: "Propose a solution to reduce traffic in busy cities.",
        focusArea: "Critical thinking and solutions",
        durationSeconds: 90,
        level: 4,
        isCompleted: false,
      },
      {
        id: "impromptu8",
        title: "Abstract Concepts",
        description: "Explain complex ideas simply",
        prompt: "Define what success means to you in your own words.",
        focusArea: "Conceptual explanation",
        durationSeconds: 60,
        level: 4,
        isCompleted: false,
      },
      {
        id: "impromptu9",
        title: "Rapid Response",
        description: "React quickly to unexpected topics",
        prompt: "What would you do if you suddenly had to give a speech with no preparation?",
        focusArea: "Adaptability",
        durationSeconds: 90,
        level: 5,
        isCompleted: false,
      },
      {
        id: "impromptu10",
        title: "Elevator Pitch",
        description: "Sell yourself or an idea quickly",
        prompt: "Give a 30-second elevator pitch for your dream job.",
        focusArea: "Concise persuasion",
        durationSeconds: 30,
        level: 5,
        isCompleted: false,
      },
    ],
  },
  {
    id: "persuasive",
    name: "Persuasive Speaking",
    description: "Learn to convince and influence others",
    icon: "🎯",
    color: "bg-lingo-green",
    image: "/placeholder.svg",
    requiredLevel: 1,
    lessons: [
      {
        id: "persuasive1",
        title: "Simple Persuasion",
        description: "Make a fun case for something you enjoy",
        prompt: "Convince me why pizza is the best food in the world (30 seconds).",
        focusArea: "Simple persuasive language",
        durationSeconds: 30,
        level: 1,
        isCompleted: false,
      },
      {
        id: "persuasive2",
        title: "Recommendation",
        description: "Recommend something you enjoy",
        prompt: "Try to persuade me to read your favorite book (45 seconds).",
        focusArea: "Highlighting benefits",
        durationSeconds: 45,
        level: 1,
        isCompleted: false,
      },
      {
        id: "persuasive3",
        title: "Friend Pitch",
        description: "Persuade a friend to join an activity",
        prompt: "Make a short pitch to convince a friend to try a new activity with you (1 minute).",
        focusArea: "Call to action",
        durationSeconds: 60,
        level: 2,
        isCompleted: false,
      },
      {
        id: "persuasive4",
        title: "Environmental Awareness",
        description: "Make a case for environmental action",
        prompt: "Persuade your audience that recycling is important (1 minute 30 seconds).",
        focusArea: "Presenting arguments",
        durationSeconds: 90,
        level: 2,
        isCompleted: false,
      },
      {
        id: "persuasive5",
        title: "Business Case",
        description: "Present a business-oriented persuasive argument",
        prompt: "Convince a company to adopt a more sustainable practice (2 minutes).",
        focusArea: "Developing a persuasive case",
        durationSeconds: 120,
        level: 3,
        isCompleted: false,
      },
      {
        id: "persuasive6",
        title: "Passionate Argument",
        description: "Argue for something you believe in",
        prompt: "Present a short persuasive argument on a topic you feel strongly about (2 minutes 30 seconds).",
        focusArea: "Passion and conviction",
        durationSeconds: 150,
        level: 3,
        isCompleted: false,
      },
      {
        id: "persuasive7",
        title: "Consumer Persuasion",
        description: "Convince someone to make a purchase",
        prompt: "Persuade someone to buy a product you recently purchased and love.",
        focusArea: "Consumer persuasion",
        durationSeconds: 90,
        level: 4,
        isCompleted: false,
      },
      {
        id: "persuasive8",
        title: "Lifestyle Change",
        description: "Convince others to adopt a new habit",
        prompt: "Make the case for why people should adopt a healthy morning routine.",
        focusArea: "Lifestyle advocacy",
        durationSeconds: 120,
        level: 4,
        isCompleted: false,
      },
      {
        id: "persuasive9",
        title: "Policy Argument",
        description: "Argue for a policy or rule change",
        prompt: "Convince your school or workplace to implement a specific policy change.",
        focusArea: "Policy advocacy",
        durationSeconds: 180,
        level: 5,
        isCompleted: false,
      },
      {
        id: "persuasive10",
        title: "Funding Pitch",
        description: "Ask for support for an initiative",
        prompt: "Present a pitch requesting funding for a community project idea.",
        focusArea: "Resource acquisition",
        durationSeconds: 120,
        level: 5,
        isCompleted: false,
      },
    ],
  },
  {
    id: "technical",
    name: "Technical Presentations",
    description: "Explain complex topics clearly",
    icon: "💻",
    color: "bg-lingo-darkBlue",
    image: "/placeholder.svg",
    requiredLevel: 2,
    lessons: [
      {
        id: "technical1",
        title: "Define a Term",
        description: "Explain a technical term simply",
        prompt: "Explain a simple technical term (e.g., 'algorithm') in your own words for 30 seconds.",
        focusArea: "Clarity and simplification",
        durationSeconds: 30,
        level: 1,
        isCompleted: false,
      },
      {
        id: "technical2",
        title: "Process Explanation",
        description: "Describe a step-by-step process",
        prompt: "Describe the basic steps of a common process (e.g., making a cup of tea) in 45 seconds.",
        focusArea: "Sequential explanation",
        durationSeconds: 45,
        level: 1,
        isCompleted: false,
      },
      {
        id: "technical3",
        title: "Technology Benefits",
        description: "Explain advantages of technology",
        prompt: "Explain one benefit of using a specific piece of technology (1 minute).",
        focusArea: "Highlighting advantages",
        durationSeconds: 60,
        level: 2,
        isCompleted: false,
      },
      {
        id: "technical4",
        title: "Software Explanation",
        description: "Describe how software works",
        prompt: "Briefly describe the function of a common software application (1 minute 30 seconds).",
        focusArea: "Concise explanation",
        durationSeconds: 90,
        level: 2,
        isCompleted: false,
      },
      {
        id: "technical5",
        title: "Non-Technical Audience",
        description: "Explain tech to beginners",
        prompt: "Explain a technical concept to a non-technical audience in 2 minutes.",
        focusArea: "Avoiding jargon",
        durationSeconds: 120,
        level: 3,
        isCompleted: false,
      },
      {
        id: "technical6",
        title: "Product Features",
        description: "Present product features clearly",
        prompt: "Describe the key features of a product or service in a clear and concise manner (2 minutes 30 seconds).",
        focusArea: "Business communication",
        durationSeconds: 150,
        level: 3,
        isCompleted: false,
      },
      {
        id: "technical7",
        title: "How-to Explanation",
        description: "Teach someone a new skill",
        prompt: "Explain how to perform a simple task on a smartphone to an elderly person.",
        focusArea: "Instructional speaking",
        durationSeconds: 120,
        level: 4,
        isCompleted: false,
      },
      {
        id: "technical8",
        title: "Technical Comparison",
        description: "Compare similar technical options",
        prompt: "Compare and contrast two similar technologies or products.",
        focusArea: "Comparative analysis",
        durationSeconds: 150,
        level: 4,
        isCompleted: false,
      },
      {
        id: "technical9",
        title: "Troubleshooting Guide",
        description: "Explain how to fix a problem",
        prompt: "Walk through how to troubleshoot a common technical issue.",
        focusArea: "Problem-solving communication",
        durationSeconds: 120,
        level: 5,
        isCompleted: false,
      },
      {
        id: "technical10",
        title: "Future Tech Vision",
        description: "Present a vision of future technology",
        prompt: "Describe how you think a specific technology will evolve in the next 10 years.",
        focusArea: "Speculative presentation",
        durationSeconds: 180,
        level: 5,
        isCompleted: false,
      },
    ],
  },
  {
    id: "storytelling",
    name: "Storytelling",
    description: "Craft engaging narratives",
    icon: "📚",
    color: "bg-lingo-orange",
    image: "/placeholder.svg",
    requiredLevel: 2,
    lessons: [
      {
        id: "story1",
        title: "Personal Anecdote",
        description: "Share a short personal story",
        prompt: "Tell a 30-second story about a minor mishap you experienced.",
        focusArea: "Brief storytelling",
        durationSeconds: 30,
        level: 2,
        isCompleted: false,
      },
      // More lessons would be added here
    ],
  },
  {
    id: "filler",
    name: "Filler Word Reduction",
    description: "Eliminate ums, ahs, and other fillers",
    icon: "🚫",
    color: "bg-lingo-red",
    image: "/placeholder.svg",
    requiredLevel: 3,
    lessons: [
      {
        id: "filler1",
        title: "Filler Awareness",
        description: "Become conscious of your filler words",
        prompt: "Speak for 30 seconds about your day without using 'um', 'uh', or 'like'.",
        focusArea: "Filler word awareness",
        durationSeconds: 30,
        level: 3,
        isCompleted: false,
      },
      // More lessons would be added here
    ],
  },
  {
    id: "pacing",
    name: "Pacing and Fluency",
    description: "Control your speaking speed and flow",
    icon: "⏱️",
    color: "bg-lingo-blue",
    image: "/placeholder.svg", 
    requiredLevel: 4,
    lessons: [
      {
        id: "pacing1",
        title: "Slow and Clear",
        description: "Practice speaking deliberately",
        prompt: "Give directions to your favorite restaurant, speaking slowly and clearly.",
        focusArea: "Deliberate speech",
        durationSeconds: 45,
        level: 4,
        isCompleted: false,
      },
      // More lessons would be added here
    ],
  },
];

// Mock Achievements
export const mockAchievements: Achievement[] = [
  {
    id: "streak7",
    title: "7-Day Streak",
    description: "Practice for 7 days in a row",
    icon: "🔥",
    color: "bg-lingo-orange",
    isUnlocked: true,
    progress: 7,
    maxProgress: 7,
  },
  {
    id: "streak30",
    title: "30-Day Streak",
    description: "Practice for 30 days in a row",
    icon: "🔥",
    color: "bg-lingo-orange",
    isUnlocked: false,
    progress: 7,
    maxProgress: 30,
  },
  {
    id: "firstLesson",
    title: "First Steps",
    description: "Complete your first speaking lesson",
    icon: "👣",
    color: "bg-lingo-green",
    isUnlocked: true,
    progress: 1,
    maxProgress: 1,
  },
  {
    id: "levelUp",
    title: "Level Up",
    description: "Reach level 2",
    icon: "⬆️",
    color: "bg-lingo-blue",
    isUnlocked: true,
    progress: 2,
    maxProgress: 2,
  },
  {
    id: "tenLessons",
    title: "Dedicated Speaker",
    description: "Complete 10 speaking lessons",
    icon: "🎓",
    color: "bg-lingo-darkBlue",
    isUnlocked: false,
    progress: 1,
    maxProgress: 10,
  },
  {
    id: "perfectScore",
    title: "Perfect Delivery",
    description: "Get a 100% score on any lesson",
    icon: "🏆",
    color: "bg-lingo-green",
    isUnlocked: false,
    progress: 0,
    maxProgress: 1,
  },
  {
    id: "noFillers",
    title: "Clear Speech",
    description: "Complete a lesson with zero filler words",
    icon: "🎯",
    color: "bg-lingo-red",
    isUnlocked: false,
    progress: 0,
    maxProgress: 1,
  },
  {
    id: "firstReferral",
    title: "Spread the Word",
    description: "Refer a friend to SpeechLingo",
    icon: "👥",
    color: "bg-lingo-blue",
    isUnlocked: true,
    progress: 2,
    maxProgress: 1,
  },
  {
    id: "hourPractice",
    title: "Hour of Power",
    description: "Accumulate 60 minutes of practice time",
    icon: "⏰",
    color: "bg-lingo-darkBlue",
    isUnlocked: true,
    progress: 128,
    maxProgress: 60,
  },
  {
    id: "completeCategory",
    title: "Category Master",
    description: "Complete all lessons in a single category",
    icon: "🎖️",
    color: "bg-lingo-green",
    isUnlocked: false,
    progress: 1,
    maxProgress: 10,
  },
];

// Mock Friends
export const mockFriends: Friend[] = [
  {
    id: "friend1",
    name: "Sarah Chen",
    avatar: "/placeholder.svg",
    level: 5,
    streak: 15,
    lastActive: "2 hours ago",
  },
  {
    id: "friend2",
    name: "Marcus Johnson",
    avatar: "/placeholder.svg",
    level: 3,
    streak: 4,
    lastActive: "1 day ago",
  },
  {
    id: "friend3",
    name: "Priya Sharma",
    avatar: "/placeholder.svg",
    level: 7,
    streak: 32,
    lastActive: "Just now",
  },
];

// Mock Activity Feed
export const mockActivity: ActivityItem[] = [
  {
    id: "activity1",
    userId: "friend1",
    userName: "Sarah Chen",
    userAvatar: "/placeholder.svg",
    action: "completed 'Impromptu Speaking' Level 3",
    timestamp: "2 hours ago",
  },
  {
    id: "activity2",
    userId: "friend3",
    userName: "Priya Sharma",
    userAvatar: "/placeholder.svg",
    action: "reached a 30-day streak! 🔥",
    timestamp: "4 hours ago",
  },
  {
    id: "activity3",
    userId: "friend2",
    userName: "Marcus Johnson",
    userAvatar: "/placeholder.svg",
    action: "unlocked the 'Clear Speech' achievement",
    timestamp: "Yesterday",
  },
  {
    id: "activity4",
    userId: "user1",
    userName: "You",
    userAvatar: "/placeholder.svg",
    action: "completed 'Impromptu Speaking' Level 1",
    timestamp: "2 days ago",
  },
];

// Motivational Quotes
export const motivationalQuotes = [
  {
    quote: "Speech is power: speech is to persuade, to convert, to compel.",
    author: "Ralph Waldo Emerson"
  },
  {
    quote: "If you can speak, you can influence. If you can influence, you can change lives.",
    author: "Rob Brown"
  },
  {
    quote: "The human voice is the most perfect instrument of all.",
    author: "Arvo Pärt"
  },
  {
    quote: "Speech is the mirror of the soul; as a man speaks, so is he.",
    author: "Publilius Syrus"
  },
  {
    quote: "The way you tell your story to yourself matters.",
    author: "Amy Cuddy"
  },
  {
    quote: "Words have energy and power with the ability to help, to heal, to hinder, to hurt, to harm, to humiliate, and to humble.",
    author: "Yehuda Berg"
  },
  {
    quote: "The most precious things in speech are pauses.",
    author: "Ralph Richardson"
  },
  {
    quote: "A good speech should be like a woman's skirt: long enough to cover the subject and short enough to create interest.",
    author: "Winston Churchill"
  },
  {
    quote: "Words mean more than what is set down on paper. It takes the human voice to infuse them with deeper meaning.",
    author: "Maya Angelou"
  },
  {
    quote: "Think like a wise man but communicate in the language of the people.",
    author: "William Butler Yeats"
  },
];
